# Railway deployment configuration - Updated for v0.9.0
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python railway-deploy.py"
restartPolicyType = "always"
healthcheckPath = "/"
healthcheckTimeout = 300

# Environment variables (will be overridden by Railway dashboard)
[[envs]]
name = "PORT"
value = "8000"

[[envs]]
name = "LOG_LEVEL"
value = "INFO"

[[envs]]
name = "MCP_SERVER_HOST"
value = "0.0.0.0"

[[envs]]
name = "VECTOR_DB_TYPE"
value = "faiss"

[[envs]]
name = "RAILWAY_ENVIRONMENT"
value = "production"

[[envs]]
name = "RAILWAY_PUBLIC_DOMAIN"
value = "strunz.up.railway.app"

[[envs]]
name = "RAILWAY_PRIVATE_DOMAIN"
value = "strunz.railway.internal"

[[envs]]
name = "RAILWAY_HEALTHCHECK_BASIC"
value = "true"

[[envs]]
name = "CLAUDE_AI_SKIP_OAUTH"
value = "true"